### ISSUE TITLE
Fan speed control

### ISSUE THREAD

**Issue by Anto79-ops** [BrucesHobbies/radonMaster#2]
Hi, I'd like to ask you about incorporating fan speed control into this script. Please let me know how I can contact you. thanks.

**Comment by BrucesHobbies** [comment]
Thank you for the suggestions and email. Please feel free to contact Bruce at BrucesHobbies@gmail.com.  I have added the Python script mcp4725.py to work with your mcp4725 board that you are looking at as the first step.

**Comment by BrucesHobbies** [comment]
Added a basic fan speed function that ramps the fan speed based on radon levels detected. The slope of the ramp can be adjusted based on historical data. Interested in ideas for a self-tuning intelligent algorithm.

**Comment by Anto79-ops** [comment]
thank you for the fan speed control option. it working amazing!
